config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  resources :parents

  resources :jobs

  resources :conversations do
    resources :messages
  end

  resources :users do
    member do
      get :ratings
    end
  end

  resources :requests,       only: [:create, :destroy]

  resources :ratings

  resources :relationships,       only: [:create, :destroy]

  get    'search'   => 'parents#search'

  get    'calculators'   => 'calculators#new'
  post   'calculators'  => 'calculators#create'

  post 'parents/optimize', :to => 'parents#optimize'

  patch 'requests/accept', :to => 'requests#accept'
  patch 'requests/pay', :to => 'requests#pay'

  post 'relationships/create', :to => 'relationships#create'
  patch 'relationships/destroy', :to => 'relationships#destroy'

  post 'sortings/by_created_at', :to => 'sortings#by_created_at'
  post 'sortings/by_matching', :to => 'sortings#by_matching'
  post 'sortings/by_rate', :to => 'sortings#by_rate'

  post 'matchings/match', :to => 'matchings#match'

  get    'proto_premium'   => 'static_pages#proto_premium'
  post   'static_pages/premium'   => 'static_pages#premium'
  get    'proto_pay'   => 'static_pages#proto_pay'

  get    'index'   => 'matchings#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :job, dependent: :destroy
  has_one :parent, dependent: :destroy
  has_one :calculator, dependent: :destroy

  has_many :conversations, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :ratings, foreign_key: "sender_id", dependent: :destroy
  has_many :ratings, foreign_key: "receiver_id", dependent: :destroy
  has_many :senders, through: :ratings
  has_many :receivers, through: :ratings


  has_many :active_relationships, class_name:  "Relationship",
           foreign_key: "follower_id",
           dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed


  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+[^.]\.[^.][a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?  # rest of the method gets ignored in that case
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Defines a proto_premium-feed.
  # def feed
    # following_ids = "SELECT followed_id FROM relationships
    #                  WHERE  follower_id = :user_id"
    # Micropost.where("user_id IN (#{following_ids})
    #                  OR user_id = :user_id", user_id: id)
  # end


  def user_since
    created_at.strftime("%d.%m.%y")
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,             only: [:edit, :update, :destroy,
                                                    :following, :followers, :show]
  before_action :correct_user,               only: [:edit, :update]
  before_action :correct_job,                only: :show
  before_action :access_permission_ratings,  only: :ratings
  before_action :access_permission_profiles, only: :show


  def ratings
    @user  = User.find(params[:id])
    @ratings_received = Rating.where("(receiver_id = " + @user.id.to_s + ")")
    @ratings_sent = Rating.where("(sender_id = " + @user.id.to_s + ")")

    render 'users/ratings'
  end


  def show

    @rating = Rating.new
    @ratings_received = Rating.where("(receiver_id = " + @user.id.to_s + ")")
    @user = User.find(params[:id])
    @conversations = Conversation.all

    if !@user.job.nil?
      @calendartimes = @user.job.time.split(",")
    end
    if !@user.parent.nil?
      @parent_calendartimes = @user.parent.time.split(",")
    end

    if parent?
      @potentials = current_user.parent.potential_ids
    else
      @potentials = []
    end

    if job?
      @interesteds = current_user.job.interested_ids
    else
      @interesteds = []
    end

    if !current_user.messages.nil?
      last_conversation = Conversation.where("(parent_user_id = " + current_user.id.to_s + ") or (job_user_id = " + current_user.id.to_s + ")").last
      if !last_conversation.nil?
        @last_message = last_conversation.messages.last
      end
    else
      @last_message = []
    end
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Mailer kann durch unkommentieren angesprochen werden
      # UserMailer.welcome_email(@user).deliver_now
      log_in(@user)
      flash[:success] = "Willkommen bei BabyRitter"
      redirect_back_or @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Userprofil aktualisiert"
      redirect_to @user
    else
      render 'edit'
    end
  end


    private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

   # availability only visible if matched
    def correct_job
      if (parent? && !current_user.parent.sorting.nil?)
        assigned_nanny_users = current_user.parent.sorting.helpfield.split(",")
        if assigned_nanny_users.include?(params[:id])
          @correct_nanny = true
        else
          @correct_nanny = false
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Nutzerdaten ändern") %>


<div class="row">
  <div class="col-xs-2"></div>
  <div class="col-xs-8 greyBox">
    <h1>Account Einstellungen ändern</h1>
    <div class="row whiteBox">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :passwort %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Passwort bestätigen" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Änderungen speichern", class: "btn btn-primary" %>
        <% end %>
        <div class="gravatar_edit">
          <%= gravatar_for @user %>
          <a href="http://gravatar.com/emails" target="_blank">Bild ändern</a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-2"></div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-xs-2">
  </div>
  <div class="col-xs-8 greyBox">
    <h1>Account erstellen</h1>
    <div class="row whiteBox">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :Passwort %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Passwort bestätigen" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Account erstellen", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-xs-2">
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div class="row">
  <div class="col-xs-1"></div>
  <div class="col-xs-10 <%= (current_user.premium? && current_user?(@user)) ? "premiumBox" : "userBox" %>">

    <div class="row userInfoBox">
      <div class="col-xs-6">
        <div class="userPic">
          <%= gravatar_for @user, size: 100 %>
        </div>
        <div class ="userName">
          <%= @user.name %>
        </div>
        Mitglied seit dem:
        <div><%= @user.user_since %></div>
      </div>

      <% if !((job? or parent?) or current_user.admin?) %>
          <div class="col-xs-6">
            <div style="padding:6px 0 12px 0;">Sie haben noch kein Profil erstellt. <br />
              Wählen Sie ihr Team.</div>
            <%= link_to "Nanny", new_job_path, class: "btn btn-lg btn-primary smallerStartPageButtonNanny" %>
            <%= link_to "Eltern", new_parent_path, class: "btn btn-lg btn-primary smallerStartPageButtonParent" %>
          </div>
      <% end %>
      <div class="col-xs-6 matchedNanniesButtons">
        <% if (@user != current_user) and parent? and !@user.job.nil? and
            (current_user.premium? or (@user.id == current_user.parent.assigned.to_i)) %>
            <% if current_user.premium? %>
                <div style="display:inline-block">
                  <% if current_user.following?(@user) %>
                      <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                                   html: { method: :delete }) do |f|  %>
                          <%= hidden_field_tag(:the_requested_user, @user.id) %>
                          <%= hidden_field_tag(:redirecter, 'back_to_user') %>
                          <%= button_tag(type: "submit", class: "btn btn-danger") do %>
                              <span><i class="glyphicon glyphicon-heart-empty"></i> Vergessen</span>
                          <% end %>
                      <% end %>
                  <% else %>
                      <%= form_for(current_user.active_relationships.build,
                                   :url => url_for(:controller => 'relationships', :action => 'create')) do |f| %>
                          <%= hidden_field_tag :followed_id, @user.id %>
                          <%= hidden_field_tag(:redirecter, 'back_to_user') %>
                          <%= button_tag(type: "submit", class: "btn btn-default") do %>
                              <span><i class="glyphicon glyphicon-heart"></i> Merken</span>
                          <% end %>
                      <% end %>
                  <% end %>
                </div>
            <% end %>

            <div style="display:inline-block">
                <%= link_to conversations_path(parent_user_id: current_user.id, job_user_id: @user.id),
                            method: "post", :class => "btn btn-default" do %>
                    <span class="glyphicon glyphicon-envelope"></span> Kontakt
                <% end %>
            </div>

            <div style="display:inline-block">
              <% request = current_user.parent.active_requests.find_by(potential_id: @user.job.id) %>
              <% if !request.nil? and !request.paid? and !request.accepted? %>
                  <%= form_for(current_user.parent.active_requests.find_by(potential_id: @user.job.id),
                               html: { method: :delete }) do |f| %>
                      <%= hidden_field_tag(:the_requested_user, @user.id) %>
                      <%= hidden_field_tag(:redirecter, 'back_to_user') %>
                      <%= button_tag(type: "submit", class: "btn btn-success") do %>
                          <span><i class="glyphicon glyphicon-circle-arrow-down"></i> Anfrage zurück</span>
                      <% end %>
                  <% end %>
              <% end %>
              <% if !request.nil? and !request.paid? and request.accepted? %>
                  <%= form_for(request, :url => url_for(:controller => 'requests', :action => 'pay')) do |f| %>
                      <%= hidden_field_tag(:request_id, request.id) %>
                      <%= button_tag(type: "submit", class: "btn btn-primary",
                                     :data => {:confirm => 'Wenn Sie diese Nanny buchen, werden alle offenen Anfragen gelöscht. Möchten Sie fortfahren?'})  do %>
                          <span><i class="glyphicon glyphicon-euro"></i> Bezahlen</span>
                      <% end %>
                  <% end %>
              <% end %>
              <!--Wenn keine Anfrage besteht ODER erst wenn Job abgeschlossen, dann neue Anfrage an dieselbe Nanny-->
              <% if request.nil? or (request.paid? and
                  (("20" + Time.now.strftime("%y%m%d")).to_i >= current_user.parent.valid_from.tr('-', '').to_i)) %>
                  <%= form_for current_user.parent.active_requests.build,
                               :url => url_for(:controller => 'requests', :action => 'create') do |f| %>
                      <%= f.hidden_field :potential_id, :value =>  @user.job.id%>
                      <%= f.hidden_field :start_date,:value => current_user.parent.valid_from %>
                      <%= f.hidden_field :end_date,:value => current_user.parent.valid_until %>
                      <%= f.hidden_field :time,:value => current_user.parent.time %>
                      <%= hidden_field_tag(:the_requested_user, @user.id) %>
                      <%= hidden_field_tag(:redirecter, 'back_to_user') %>
                      <%= button_tag(type: "submit", class: "btn btn-default") do %>
                          <span><i class="glyphicon glyphicon-circle-arrow-up"></i> Anfrage stellen</span>
                      <% end %>
                  <% end %>
              <% end %>
            </div>
          <% end %>

        <% if ((@user != current_user) and job?) %>
            <div style="display:inline-block">
              <%= link_to conversations_path(parent_user_id: @user.id, job_user_id: current_user.id),
                          method: "post", :class => "btn btn-default" do %>
                  <span class="glyphicon glyphicon-envelope"></span> Kontakt
              <% end %>
            </div>
        <% end %>

        <div class="premiumButton">
          <% if current_user?(@user) and parent? %>
              <div class="premiumAlign">
                <% if !current_user.premium? %>
                    <%= link_to "Premium upgrade", proto_premium_path , :class => "btn btn-warning" %>
                <% else %>
                    <div class="glyphicon glyphicon-star"></div>
                    <div><strong>Premium</strong></div>
                <% end %>
              </div>
        <% end %>
        </div>
      </div>
    </div>

    <% if !@user.job.nil? %>
      <div class="whiteBox">
        <% if current_user?(@user) %><div class="headline">Mein Nannyprofil</div>
        <% else %><div class="headline">Nannyprofil</div>
        <% end %>
        <%= render 'shared/job'%>
        <% if @correct_nanny or current_user?(@user) or current_user.premium? or current_user.admin? or
            (parent? and !current_user.parent.assigned.nil? and current_user.parent.assigned.to_i == @user.id.to_i) %>
            <div class="availabilityBox">
              <%= render 'shared/availability'%>
            </div>
        <% end %>
      </div>
    <% end %>

    <% if (current_user.admin? and !@user.parent.nil?) or (parent? and current_user?(@user)) or
        (job? and(current_user.job.interesteds.include?(@user.parent)))%>
      <div class="whiteBox">
        <% if current_user?(@user) %><div class="headline">Mein Elternprofil</div>
        <% else %><div class="headline">Elternprofil</div>
        <% end %>
        <%= render 'shared/parent' %>
      </div>
    <% end %>

    <% if (current_user.admin? and !@user.parent.nil?) or
        (parent? and !current_user.premium? and current_user?(@user)) %>
        <hr class ="orangeLine">
        <div class="whiteBox">
          <% if current_user.admin? %><div class="headline">Matching</div><% else %>
              <div class="headline">Mein Matching</div><% end %>
          <% if @user.parent.assigned.nil? or (@user.parent.assigned.to_i == 0) %>
              <h4>Derzeit kein Matching</h4>
          <% else %>
              <%= render 'shared/matched' %>
          <% end %>
        </div>
    <% end %>

    <% if parent? and current_user?(@user) and @potentials.any? %>
        <hr class ="orangeLine">
        <div class=" potentialsBox">
          <div class="headline">Meine Anfragen</div>
          <%= render 'shared/potentials' %>
        </div>
    <% end %>

    <% if job? and current_user?(@user) and @interesteds.any? %>
        <hr class ="orangeLine">
        <div class="whiteBox" style="display: block">
          <div class="headline">Meine Anfragen</div>
          <%= render 'shared/interesteds' %>
        </div>
    <% end %>

    <% if parent? and current_user?(@user) and current_user.following.any? and current_user.premium? %>
        <hr class ="orangeLine">
        <div class="whiteBox">
          <div class="headline">Nanny-Merkliste</div>
            <% current_user.following.each do |user| %>
              <div class="eachOnRemeberList">
                <%= link_to gravatar_for(user, size: 60), user %>
                <a href="<%=user.id%>">
                  <%= user.name %></a>
              </div>
            <% end %>
        </div>
    <% end %>

    <% if current_user?(@user)%>
        <hr class ="orangeLine">
        <div class="whiteBox">
          <% if current_user.admin? %>
              <div class="headline">Admin Mailbox</div>
          <% else %>
              <div class="headline">Meine Mailbox</div>
          <% end %>
          <%= render 'conversations/mailbox' %>
        </div>
    <% end %>

    <% if !(current_user?(@user) and current_user.admin?)%>
    <hr class="orangeLine">
    <div class="whiteBox">
      <% if current_user?(@user) %><div class="headline">Meine Bewertungen</div><% else %>
          <div class="headline">Bewertungen</div><% end %>
      <%= render 'shared/rating' %>
    </div>
    <% end %>
  </div>
  <div class="col-xs-1"></div>
</div>
