config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  resources :parents

  resources :jobs

  resources :conversations do
    resources :messages
  end

  resources :users do
    member do
      get :ratings
    end
  end

  resources :requests,       only: [:create, :destroy]

  resources :ratings

  resources :relationships,       only: [:create, :destroy]

  get    'search'   => 'parents#search'

  get    'calculators'   => 'calculators#new'
  post   'calculators'  => 'calculators#create'

  post 'parents/optimize', :to => 'parents#optimize'

  patch 'requests/accept', :to => 'requests#accept'
  patch 'requests/pay', :to => 'requests#pay'

  post 'relationships/create', :to => 'relationships#create'
  patch 'relationships/destroy', :to => 'relationships#destroy'

  post 'sortings/by_created_at', :to => 'sortings#by_created_at'
  post 'sortings/by_matching', :to => 'sortings#by_matching'
  post 'sortings/by_rate', :to => 'sortings#by_rate'

  post 'matchings/match', :to => 'matchings#match'

  get    'proto_premium'   => 'static_pages#proto_premium'
  post   'static_pages/premium'   => 'static_pages#premium'
  get    'proto_pay'   => 'static_pages#proto_pay'

  get    'index'   => 'matchings#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="error_explanation">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_job.html.erb
<div class="row">
  <% if current_user?(@user)%>
      <div class="btn-group cogButton">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-cog"></span>   <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <% if current_user.job.passive_requests.where("(paid = 'f')").any? %>
            <%= link_to edit_job_path, :data => {:confirm => 'Sie haben offene Anfragen. Wenn Sie ihr Nannyprofil editieren, werden offene Anfragen gelöscht.'} do %>
                    <span class="glyphicon glyphicon-pencil"></span> Editieren<% end %>
            <% else %>
                <%= link_to edit_job_path do %>
                    <span class="glyphicon glyphicon-pencil"></span> Editieren<% end %>
            <% end %>
          </li>
        </ul>
      </div>

  <% end %>
  <div class="col-xs-1"></div>
  <div class="col-xs-11">
    <div class="row profileAgeAndCity">
      <div class="col-xs-3 ageColumn">
        Alter: <%=@user.job.age%>
      </div>
      <div class="col-xs-3 cityColumn">
        wohnt in: <%=@user.job.city%>
      </div>
      <div class="col-xs-3 rateColumn">
        Stundenlohn: <%=@user.job.rate%> €
      </div>
      <div class="col-xs-3"></div>
    </div>
    <div class="row profileContent">
      <div class="col-xs-9">
        <%= @user.job.content %>
        <div class="profileCreatedAt">Zuletzt aktualisiert vor <%= time_ago_in_words(@user.job.updated_at) %>.</div>
      </div>
      <div class="col-xs-3"></div>
    </div>
    <div class="row profileAttributes">
      <div class="col-xs-5">
        <ul>
          <% if @user.job.experience == 2 %><li>1-2 Jahre Erfahrung als Nanny</li><% end %>
          <% if @user.job.experience == 3 %><li>3-4 Jahre Erfahrung als Nanny</li><% end %>
          <% if @user.job.experience == 4 %><li>über 5 Jahre Erfahrung als Nanny</li><% end %>
          <% if @user.job.car == true %><li>hat ein eigenes Auto</li><% end %>
          <% if !(@user.job.time.split(",") & ["1","2","3","4","5","6","7"]).empty? %><li>ist vormittags verfügbar</li><% end %>
          <% if !(@user.job.time.split(",") & ["29","30","31","32","33","34","35"]).empty? %><li>kann über Nacht bleiben</li><% end %>
          <% if !(@user.job.time.split(",") & ["6","7","13","14","20","21","27","28","34","35"]).empty? %><li>kann auch am Wochenende</li><% end %>
          <% if @user.job.kids == 1 %><li>bietet Betreuung für ein Kind<% end %>
          <% if @user.job.kids == 2 %><li>bietet Betreuung für bis zu zwei Kindern<% end %>
          <% if @user.job.kids == 3 %><li>bietet Betreuung für bis zu drei Kindern<% end %>
          <% if @user.job.kids == 4 %><li>bietet Betreuung für vier oder mehr Kinder<% end %>
          <ul>
            <% if @user.job.baby? and @user.job.toddler? and @user.job.preschooler? and
                @user.job.gradeschooler? and @user.job.teenager? %><li>für alle Altersstufen</li>
            <%else%>
                <% if @user.job.baby? %><li> Babies (0-1) </li><% end %>
                <% if @user.job.toddler? %><li> Kleinkinder (1-3) </li><% end %>
                <% if @user.job.preschooler? %><li> Vorschüler (3-5) </li><% end %>
                <% if @user.job.gradeschooler? %><li> Grundschüler (5-12) </li><% end %>
                <% if @user.job.teenager? %><li> Teenager (12+) </li><% end %>
            <% end %>
          </ul>
          </li>
        </ul>
      </div>
      <div class="col-xs-5">
        <ul>
        <li>Ich biete:
          <ul>
            <% if @user.job.homework? %><li> Hausaufgabenhilfe </li><% end %>
            <% if @user.job.laundry? %><li> Wäsche waschen </li><% end %>
            <% if @user.job.run_errands? %><li> Kleine Besorgungen erledigen </li><% end %>
            <% if @user.job.to_bed? %><li> Ins Bett bringen </li><% end %>
            <% if @user.job.cooking? %><li> Kochen </li><% end %>
            <% if @user.job.bodycare? %><li> Körperpflege (Duschen, wickeln, etc.) </li><% end %>
            <% if @user.job.feed? %><li> Füttern </li><% end %>
            <% if @user.job.read? %><li> Vorlesen </li><% end %>
            <% if @user.job.sports? %><li> mit dem Kind Sport machen </li><% end %>
            <% if @user.job.swimming? %><li> Schwimmen gehen </li><% end %>
            <% if @user.job.painting? %><li> Malen und Zeichnen </li><% end %>
            <% if @user.job.excursions? %><li> Ausflüge unternehmen </li><% end %>
          </ul>
        </li>
        </ul>
      </div>
      <div class="col-xs-2"></div>
    </div>
  </div>
</div>

app/views/shared/_matched.html.erb
<% user = User.find_by(id:@user.parent.assigned.to_i) %>

<div class="row eachRequest">
  <div class="col-xs-4" style="text-align: left">
    <a href="../users/<%= user.id %>">
      <%= gravatar_for user, size: 60 %></a>
    <a href="../users/<%= user.id %>">
      <%= user.name %></a>
  </div>
  <div class="col-xs-8 matchedNanniesButtons">
    <% unless current_user.admin? %>
    <div style="display:inline-block">
      <%= link_to conversations_path(parent_user_id: current_user.id, job_user_id: user.id),
                  method: "post", :class => "btn btn-default" do %>
          <span class="glyphicon glyphicon-envelope"></span> Kontakt
      <% end %>
    </div>
    <% end %>
    <div style="display:inline-block">
      <%= link_to user, class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-user"></i> Zum Profil
      <% end %>
    </div>
  </div>
</div>

<div class="row profileAgeAndCity">
  <div class="col-xs-3 ageColumn">
    Alter: <%= user.job.age %>
  </div>
  <div class="col-xs-3 cityColumn">
    wohnt in: <%= user.job.city %>
  </div>
  <div class="col-xs-3 rateColumn">
    Stundenlohn: <%= user.job.rate %> €
  </div>
  <div class="col-xs-3"></div>
</div>

<div class="row profileContent">
  <div class="col-xs-9">
    <%= user.job.content %>
    <div class="profileCreatedAt">Zuletzt aktualisiert vor <%= time_ago_in_words(user.job.updated_at) %>.</div>
  </div>
  <div class="col-xs-3"></div>
</div>


app/views/shared/_parent.html.erb
<div class="row">

  <% if current_user?(@user) %>
      <div class="btn-group cogButton">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-cog"></span>   <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to edit_parent_path, :data => {:confirm => 'Elternprofil editieren? Matchings und offene Anfragen werden gelöscht.'} do%>
                <span class="glyphicon glyphicon-pencil"></span> Editieren<% end %>
          </li>
        </ul>
      </div>
  <% end %>

  <div class="col-xs-1"></div>
  <div class="col-xs-11">
    <div class="row profileAgeAndCity">
      <div class="col-xs-3 cityColumn">
        wohnt in: <%=@user.parent.city%>
      </div>
      <div class="col-xs-3 ageColumn">
        Nanny gesucht für <%if(@user.parent.kids.to_i > 1)%><%=@user.parent.kids%> Kinder<%else%> 1 Kind<% end %>
      </div>
      <div class="col-xs-1 ageColumn" style="text-align: center;">
        Alter:
      </div>
      <div class="col-xs-5 kidsColumn">
        <div><% if @user.parent.baby? %> Baby (0-1 Jahre) <% end %></div>
        <div><% if @user.parent.toddler? %> Kleinkind (1-3 Jahre)<% end %></div>
        <div><% if @user.parent.preschooler? %>Vorschüler (3-5 Jahre)<% end %></div>
        <div><% if @user.parent.gradeschooler? %> Grundschüler (5-12 Jahre)<% end %></div>
        <div><% if @user.parent.teenager? %> Teenager (12+ Jahre) <% end %></div>
      </div>
    </div>

    <div class="row profileContent">
      <div class="col-xs-9">
        <%=@user.parent.content %>
        <div class="profileCreatedAt">Erstellt vor <%= time_ago_in_words(@user.parent.created_at) %>.</div>
      </div>
      <div class="col-xs-3"></div>
    </div>

    <div class="row profileAttributes">
      <div class="col-xs-1"></div>
       <div class="col-xs-5">
        <ul>
          <% if @user.parent.pets? %><li> Wir haben Haustiere </li><% end %>
          <% if @user.parent.nonsmoker?%><li> Nur Nichtraucher <% end %>
          <% if @user.parent.licence > 2 %><li> Ein Führerschein wird benötigt </li><% end %>
          <% if @user.parent.car > 2 %><li> Ein eigenes Auto wird benötigt </li><% end %>
        </ul>
      </div>
      <div class="col-xs-5">
        <% if @user.parent.homework > 2 || @user.parent.laundry > 2 || @user.parent.run_errands > 2 || @user.parent.to_bed > 2 ||
            @user.parent.cooking > 2 || @user.parent.bodycare > 2 || @user.parent.feed > 2 || @user.parent.read > 2 ||
            @user.parent.sports > 2 || @user.parent.swimming > 2 || @user.parent.painting > 2 || @user.parent.excursions > 2 %>
        <ul>
          <li>Voraussetzungen:
            <ul>
              <% if @user.parent.homework > 2 %><li> Hausaufgabenhilfe geben </li><% end %>
              <% if @user.parent.laundry > 2 %><li> Wäsche waschen </li><% end %>
              <% if @user.parent.run_errands > 2 %><li> Kleine Besorgungen erledigen </li><% end %>
              <% if @user.parent.to_bed > 2 %><li> Ins Bett bringen </li><% end %>
              <% if @user.parent.cooking > 2 %><li> Kochen </li><% end %>
              <% if @user.parent.bodycare > 2 %><li> Körperpflege (Duschen, wickeln, etc.) </li><% end %>
              <% if @user.parent.feed > 2 %><li> Füttern </li><% end %>
              <% if @user.parent.read > 2 %><li> Vorlesen </li><% end %>
              <% if @user.parent.sports > 2 %><li> mit dem Kind Sport machen </li><% end %>
              <% if @user.parent.swimming > 2 %><li> Schwimmen gehen </li><% end %>
              <% if @user.parent.painting > 2 %><li> Malen und Zeichnen </li><% end %>
              <% if @user.parent.excursions > 2 %><li> Ausflüge unternehmen </li><% end %>
            </ul>
          </li>
        </ul>
        <% end %>
      </div>
      <div class="col-xs-1"></div>
    </div>

    <div class="row availabilityBox">
        <div class="col-xs-1"></div>
        <div class="col-xs-10 availabilityTableOuter">
          <div class ="row validTimes">
            <div class="col-xs-9" style="padding-bottom:12px">
              <% if (@user.parent.valid_until == @user.parent.valid_from) %>
                  Nanny gesucht: einmalig für den <%=@user.parent.valid_from.tr('-', '').unpack('A4A2A2').reverse.join('.')%>
              <% else %>
                  Nanny gesucht im Zeitraum von: <%=@user.parent.valid_from.tr('-', '').unpack('A4A2A2').reverse.join('.')%>
                              bis <%=@user.parent.valid_until.tr('-', '').unpack('A4A2A2').reverse.join('.')%>
              <% end %>
            </div>
            <div class="col-xs-3"></div>
          </div>
          <div class="availabilityCalendar">
            <div class="row calendarRow">
              <div class="col-xs-1"></div>
              <div class="col-xs-3 calendarWeekendSideColumn"></div>
              <div class="col-xs-1 calendarWeekdayColumn">Mo</div>
              <div class="col-xs-1 calendarWeekdayColumn">Di</div>
              <div class="col-xs-1 calendarWeekdayColumn">Mi</div>
              <div class="col-xs-1 calendarWeekdayColumn">Do</div>
              <div class="col-xs-1 calendarWeekdayColumn">Fr</div>
              <div class="col-xs-1 calendarWeekendColumn">Sa</div>
              <div class="col-xs-1 calendarWeekendColumn">So</div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row calendarRow">
              <div class="col-xs-1"></div>
              <div class="col-xs-3 calendarSideColumn">Vormittags</div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('1') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('2') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('3') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('4') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('5') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('6') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('7') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row">
              <div class="col-xs-1"></div>
              <div class="col-xs-3 calendarSideColumn">Über Mittag</div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('8') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('9') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('10') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('11') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('12') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('13') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('14') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row">
              <div class="col-xs-1"></div>
              <div class="col-xs-3 calendarSideColumn">Nachmittags</div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('15') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('16') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('17') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('18') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('19') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('20') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('21') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row">
              <div class="col-xs-1"></div>
              <div class="col-xs-3 calendarSideColumn">Abends</div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('22') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('23') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('24') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('25') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('26') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('27') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('28') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1"></div>
            </div>
            <div class="row">
              <div class="col-xs-1"></div>
              <div class="col-xs-3 calendarSideColumn">Über Nacht</div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('29') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('30') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('31') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('32') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('33') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('34') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1 calendarColumn" style="<%= @parent_calendartimes.include?('35') ? 'background-color:#D7F0DA' : "" %>"></div>
              <div class="col-xs-1"></div>
            </div>
          </div>
        </div>
      <div class="col-xs-1"></div>
    </div>
  </div>
</div>


app/views/shared/_rating.html.erb
<% if !@ratings_received.any? %>
    <h4>Keine Bewertungen</h4>
<% else %>

    <% mean_parent_tidiness = (@ratings_received.sum(:parent_tidiness).to_f / @ratings_received.length.to_f).round(0).to_i %>
    <% mean_parent_correctness = (@ratings_received.sum(:parent_correctness).to_f / @ratings_received.length.to_f).round(0).to_i %>
    <% mean_parent_kindness = (@ratings_received.sum(:parent_kindness).to_f / @ratings_received.length.to_f).round(0).to_i %>
    <% mean_parent_recommendation = (@ratings_received.sum(:parent_recommendation).to_f / @ratings_received.length.to_f).round(0).to_i %>

    <% mean_job_punctuality = (@ratings_received.sum(:job_punctuality).to_f / @ratings_received.length.to_f).round(0).to_i %>
    <% mean_job_correctness = (@ratings_received.sum(:job_correctness).to_f / @ratings_received.length.to_f).round(0).to_i %>
    <% mean_job_satisfaction_of_child = (@ratings_received.sum(:job_satisfaction_of_child).to_f / @ratings_received.length.to_f).round(0).to_i %>
    <% mean_job_recommendation = (@ratings_received.sum(:job_recommendation).to_f / @ratings_received.length.to_f).round(0).to_i %>
    

<div class="row profileRating">
  <div class="col-xs-3">
    <div class  ="col-xs-3 mailboxLink">

      <% if logged_in? and (current_user?(@user) or current_user.admin? or
          (parent? and current_user.premium? and !current_user.parent.sorting.nil? and
              current_user.parent.sorting.helpfield.split(",").include?(@user.id.to_s)) or
          (parent? and current_user.premium? and !@user.job.nil? and !current_user.parent.active_requests.nil? and
              !current_user.parent.active_requests.where("(paid = 't')").nil? and
              current_user.parent.active_requests.where("(paid = 't')").pluck(:potential_id).include?(@user.job.id)) or
          (job? and !current_user.job.passive_requests.nil? and !@user.parent.nil? and
              !current_user.job.passive_requests.find_by(interested_id: @user.parent.id).nil?) or
          (!current_user.active_relationships.nil? and
              !current_user.active_relationships.find_by(followed_id: @user.id).nil?)) %>

          <%= link_to "ansehen", ratings_user_path, style: "display:inline-block; font-size:16px"  %>
      <% end %>
    </div>
  </div>
      <div class="col-xs-3" style="text-align: right">
        <br/><div class="ratingsCounter"></div>
        <% if !@user.job.nil? %>
            <div>Pünktlichkeit</div>
            <div>Genauigkeit der Angaben</div>
            <div>Zufriedenheit des Kindes</div>
            <div>Empfehlung</div>
        <% end %>
        <% if !@user.parent.nil? %>
            <div>Sauberkeit</div>
            <div>Einhaltung der Zeiten</div>
            <div>Freundlichkeit</div>
            <div>Empfehlung</div>
        <% end %>
      </div>
      <div class="col-xs-6"style="text-align: left">
        <div class="ratingsCounter">
          <% if @ratings_received.count == 1 %>
              1 Bewertung
          <% else %>
              <%= @ratings_received.count %> Bewertungen
          <% end %>
        </div>
      <% if !@user.job.nil? %>
          <div>
            <%(1..mean_job_punctuality).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_job_punctuality..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
          <div>
            <%(1..mean_job_correctness).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_job_correctness..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
          <div>
            <%(1..mean_job_satisfaction_of_child).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_job_satisfaction_of_child..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
          <div>
            <%(1..mean_job_recommendation).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_job_recommendation..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
      <% end %>
      <% if !@user.parent.nil? %>
          <div>
            <%(1..mean_parent_tidiness.to_i).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_parent_tidiness.to_i..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
          <div>
            <%(1..mean_parent_correctness).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_parent_correctness..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
          <div>
            <%(1..mean_parent_kindness).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_parent_kindness..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
          <div>
            <%(1..mean_parent_recommendation).each do |n| %>
                <span class="glyphicon glyphicon-star"></span>
                <% n %>
            <% end %>
            <%(mean_parent_recommendation..4).each do |n| %>
                <span class="glyphicon glyphicon-star-empty"></span>
                <% n %>
            <% end %>
          </div>
      <% end %>
      </div>
</div>
<% end %>