config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  resources :parents

  resources :jobs

  resources :conversations do
    resources :messages
  end

  resources :users do
    member do
      get :ratings
    end
  end

  resources :requests,       only: [:create, :destroy]

  resources :ratings

  resources :relationships,       only: [:create, :destroy]

  get    'search'   => 'parents#search'

  get    'calculators'   => 'calculators#new'
  post   'calculators'  => 'calculators#create'

  post 'parents/optimize', :to => 'parents#optimize'

  patch 'requests/accept', :to => 'requests#accept'
  patch 'requests/pay', :to => 'requests#pay'

  post 'relationships/create', :to => 'relationships#create'
  patch 'relationships/destroy', :to => 'relationships#destroy'

  post 'sortings/by_created_at', :to => 'sortings#by_created_at'
  post 'sortings/by_matching', :to => 'sortings#by_matching'
  post 'sortings/by_rate', :to => 'sortings#by_rate'

  post 'matchings/match', :to => 'matchings#match'

  get    'proto_premium'   => 'static_pages#proto_premium'
  post   'static_pages/premium'   => 'static_pages#premium'
  get    'proto_pay'   => 'static_pages#proto_pay'

  get    'index'   => 'matchings#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    BabyRitter, von Sören Schindler und Tim Kammann
  </small>
  <nav>
    <ul>
      <li><%= link_to "Info", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to root_path, id: "logo", style:"padding:6px 0 6px 0;" do %>
        <%= image_tag 'babyritter_logo.png'%>
    <% end %>
    <nav>
      <div class="navbar-header">
        <button type="button" class=" navbar-toggle" id="btnrotate" data-toggle="collapse" data-target="#myNavbar" onclick="navcollapsetrigger()">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? and current_user.admin? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle adminButton" data-toggle="dropdown">
                  Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="matchButton">
                    <span class="optimize-btn">
                      <%= button_to "Starte Matching", {controller: "matchings", action: "match",}, {class: 'btn btn-default'} %>
                    </span>
                  </li>
                  <li class="divider"></li>
                  <li><%= link_to "Alle Nannies", jobs_path %></li>
                  <li><%= link_to "Alle Eltern", parents_path %><li>
                  <li><%= link_to "Admin Mailbox", conversations_path %></li>
                  <li><%= link_to "Matching Übersicht", index_path %><li>
                </ul>
              </li>
          <% end %>
          <% if logged_in? and parent? and current_user.premium? %>
              <li class="searchField">
                <% if !current_user.parent.sorting.nil? %>
                    <%= button_to search_path, class: "btn btn-small", style:"background-color:#FCECB2;", :method => "get" do %>
                        <i class="glyphicon glyphicon-search"></i>
                    <% end %>
                <% else %>
                    <%= form_tag(controller: "parents", action: "optimize", method: "post") do %>
                        <%= hidden_field_tag(:searchsize, 5) %>
                        <span class="optimize-btn">
                          <%= button_tag(type: "submit", controller: "parents", action: "optimize",
                                         method: "post", class: "btn btn-small", style:"background-color:#FCECB2;") do %>
                              <i class="glyphicon glyphicon-search"></i>
                              </span>
                          <% end %>
                    <% end %>
                <% end %>
              </li>
          <% end %>
          <% if logged_in? %>
              <li class="navbarButton"><%= link_to current_user do %>
                    <i class="glyphicon glyphicon-user"></i>
                <% end %></li>
              <% if !current_user.admin? %>
              <li class="navbarButton"><%= link_to ratings_user_path(current_user) do %>
                    <i class="glyphicon glyphicon-align-left"></i>
                <% end %></li>
              <% end %>
              <li class="navbarButton"><%= link_to conversations_path do %>
                     <i class="glyphicon glyphicon-envelope"></i>
                  <% end %></li>
              <li class="navbarButton"><%= link_to help_path do %>
                    <i class="glyphicon glyphicon-question-sign"></i>
                <% end %></li>
              <li class="navbarButton"><%= link_to root_path do %>
                    <i class="glyphicon glyphicon-home"></i>
                <% end %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle accountToggle" data-toggle="dropdown" style="color:white">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if parent? and current_user.premium? %>
                      <li><%= link_to proto_premium_path do %>
                            <span class="glyphicon glyphicon-star"></span> Premium verwalten
                        <% end %></li>
                  <% end %>
                  <% if parent? or current_user.admin? %>
                    <li><%= link_to calculators_path do %>
                         <span class="glyphicon glyphicon-wrench"></span> Gams Pfad
                       <% end %></li>
                  <% end %>
                  <li><%= link_to edit_user_path(current_user) do %>
                        <span class="glyphicon glyphicon-cog"></span> Einstellungen
                    <% end %></li>
                  <li class="divider"></li>
                  <li><%= link_to logout_path, method: "delete" do %>
                    <span class="glyphicon glyphicon-off"></span> Ausloggen
                  <% end %></li>
                </ul>
              </li>
          <% else %>
              <li class="navbarButton"><%= link_to help_path do %>
                    <i class="glyphicon glyphicon-question-sign"></i>
                <% end %></li>
              <li class="loginButton"><%= link_to login_path, style:"margin-top: 4px" do %>
                    <span class="glyphicon glyphicon-log-in"></span> <div class="loginButtonText">Log in</div>
                <% end %>
              </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>



<script>
  $('.optimize-btn').on("click", function() {
    $('#loading_spinner').show();
  });
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!--für den Rate-Slider-->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>

<body>

  <%= render 'layouts/header' %>

  <div class="container">
    <div class="row flashMessage">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    </div>

    <%= yield %>

    <% unless @disable_footer %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    <% end %>
  </div>

    <!--LOADING SPINNER-->
    <div id="loading_spinner" class="loading-container" style="display:none">
      <div class="loader"></div>
    </div>

</body>

</html>